language: android

android:

  components:
    - tools
    - platform-tools

    # The SDK version used to compile your project
    - android-26

    # The BuildTools version used by your project
    - build-tools-26.0.2

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

